//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Applications.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OffSync.Apps.Codegen.Infra.PlantUml.Antlr {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class ApplicationsLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		START_UML=1, END_UML=2, TITLE=3, OPEN_BRACE=4, CLOSE_BRACE=5, OPEN_PARENS=6, 
		CLOSE_PARENS=7, OPEN_BRACKET=8, CLOSE_BRACKET=9, COMMA=10, DOT=11, NAMESPACE=12, 
		DOMAIN=13, CLASS=14, COMMANDS=15, COMMAND=16, MODEL=17, RESULT=18, REQUIRED_BY=19, 
		CONFIG=20, QUERIES=21, QUERY=22, INTERFACES=23, INTERFACE=24, VOID=25, 
		BOOL=26, DATETIME=27, INT=28, STRING=29, IENUMERABLE=30, IQUERYABLE=31, 
		NULLABLE=32, ID=33, PARAMETER_NAME=34, WS=35;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"START_UML", "END_UML", "TITLE", "OPEN_BRACE", "CLOSE_BRACE", "OPEN_PARENS", 
		"CLOSE_PARENS", "OPEN_BRACKET", "CLOSE_BRACKET", "COMMA", "DOT", "NAMESPACE", 
		"DOMAIN", "CLASS", "COMMANDS", "COMMAND", "MODEL", "RESULT", "REQUIRED_BY", 
		"CONFIG", "QUERIES", "QUERY", "INTERFACES", "INTERFACE", "VOID", "BOOL", 
		"DATETIME", "INT", "STRING", "IENUMERABLE", "IQUERYABLE", "NULLABLE", 
		"ID", "PARAMETER_NAME", "WS"
	};


	public ApplicationsLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ApplicationsLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'@startuml'", "'@enduml'", "'title'", "'{'", "'}'", "'('", "')'", 
		"'<'", "'>'", "','", "'.'", "'namespace'", "'Domain'", "'class'", "'Commands'", 
		"'Command'", "'Model'", "'Result'", "'-->'", "'Config'", "'Queries'", 
		"'Query'", "'Interfaces'", "'interface'", "'void'", "'bool'", "'datetime'", 
		"'int'", "'string'", "'IEnumerable'", "'IQueryable'", "'?'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "START_UML", "END_UML", "TITLE", "OPEN_BRACE", "CLOSE_BRACE", "OPEN_PARENS", 
		"CLOSE_PARENS", "OPEN_BRACKET", "CLOSE_BRACKET", "COMMA", "DOT", "NAMESPACE", 
		"DOMAIN", "CLASS", "COMMANDS", "COMMAND", "MODEL", "RESULT", "REQUIRED_BY", 
		"CONFIG", "QUERIES", "QUERY", "INTERFACES", "INTERFACE", "VOID", "BOOL", 
		"DATETIME", "INT", "STRING", "IENUMERABLE", "IQUERYABLE", "NULLABLE", 
		"ID", "PARAMETER_NAME", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Applications.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ApplicationsLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '%', '\x120', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', 
		'\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', 
		' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', 
		' ', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\a', '\"', '\x10E', 
		'\n', '\"', '\f', '\"', '\xE', '\"', '\x111', '\v', '\"', '\x3', '#', 
		'\x3', '#', '\a', '#', '\x115', '\n', '#', '\f', '#', '\xE', '#', '\x118', 
		'\v', '#', '\x3', '$', '\x6', '$', '\x11B', '\n', '$', '\r', '$', '\xE', 
		'$', '\x11C', '\x3', '$', '\x3', '$', '\x2', '\x2', '%', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', 
		'\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', '\x43', 
		'#', '\x45', '$', 'G', '%', '\x3', '\x2', '\x6', '\x3', '\x2', '\x43', 
		'\\', '\x5', '\x2', '\x32', ';', '\x43', '\\', '\x63', '|', '\x3', '\x2', 
		'\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', 
		'\x122', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', 
		'\x3', 'I', '\x3', '\x2', '\x2', '\x2', '\x5', 'S', '\x3', '\x2', '\x2', 
		'\x2', '\a', '[', '\x3', '\x2', '\x2', '\x2', '\t', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '\v', '\x63', '\x3', '\x2', '\x2', '\x2', '\r', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '\xF', 'g', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'i', '\x3', '\x2', '\x2', '\x2', '\x13', 'k', '\x3', '\x2', '\x2', '\x2', 
		'\x15', 'm', '\x3', '\x2', '\x2', '\x2', '\x17', 'o', '\x3', '\x2', '\x2', 
		'\x2', '\x19', 'q', '\x3', '\x2', '\x2', '\x2', '\x1B', '{', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x82', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x88', 
		'\x3', '\x2', '\x2', '\x2', '!', '\x91', '\x3', '\x2', '\x2', '\x2', '#', 
		'\x99', '\x3', '\x2', '\x2', '\x2', '%', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\xA6', '\x3', '\x2', '\x2', '\x2', ')', '\xAA', '\x3', '\x2', 
		'\x2', '\x2', '+', '\xB1', '\x3', '\x2', '\x2', '\x2', '-', '\xB9', '\x3', 
		'\x2', '\x2', '\x2', '/', '\xBF', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\x33', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xD9', '\x3', '\x2', '\x2', '\x2', '\x37', '\xDE', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xE7', '\x3', '\x2', '\x2', '\x2', ';', 
		'\xEB', '\x3', '\x2', '\x2', '\x2', '=', '\xF2', '\x3', '\x2', '\x2', 
		'\x2', '?', '\xFE', '\x3', '\x2', '\x2', '\x2', '\x41', '\x109', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x10B', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x112', '\x3', '\x2', '\x2', '\x2', 'G', '\x11A', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'J', '\a', '\x42', '\x2', '\x2', 'J', 'K', '\a', 'u', '\x2', 
		'\x2', 'K', 'L', '\a', 'v', '\x2', '\x2', 'L', 'M', '\a', '\x63', '\x2', 
		'\x2', 'M', 'N', '\a', 't', '\x2', '\x2', 'N', 'O', '\a', 'v', '\x2', 
		'\x2', 'O', 'P', '\a', 'w', '\x2', '\x2', 'P', 'Q', '\a', 'o', '\x2', 
		'\x2', 'Q', 'R', '\a', 'n', '\x2', '\x2', 'R', '\x4', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'T', '\a', '\x42', '\x2', '\x2', 'T', 'U', '\a', 'g', '\x2', 
		'\x2', 'U', 'V', '\a', 'p', '\x2', '\x2', 'V', 'W', '\a', '\x66', '\x2', 
		'\x2', 'W', 'X', '\a', 'w', '\x2', '\x2', 'X', 'Y', '\a', 'o', '\x2', 
		'\x2', 'Y', 'Z', '\a', 'n', '\x2', '\x2', 'Z', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\a', 'v', '\x2', '\x2', '\\', ']', '\a', 'k', '\x2', 
		'\x2', ']', '^', '\a', 'v', '\x2', '\x2', '^', '_', '\a', 'n', '\x2', 
		'\x2', '_', '`', '\a', 'g', '\x2', '\x2', '`', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x62', '\a', '}', '\x2', '\x2', '\x62', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x63', '\x64', '\a', '\x7F', '\x2', '\x2', '\x64', '\f', 
		'\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', '*', '\x2', '\x2', '\x66', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '+', '\x2', '\x2', 
		'h', '\x10', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '>', '\x2', '\x2', 
		'j', '\x12', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', '@', '\x2', '\x2', 
		'l', '\x14', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\a', '.', '\x2', '\x2', 
		'n', '\x16', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\a', '\x30', '\x2', 
		'\x2', 'p', '\x18', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\a', 'p', '\x2', 
		'\x2', 'r', 's', '\a', '\x63', '\x2', '\x2', 's', 't', '\a', 'o', '\x2', 
		'\x2', 't', 'u', '\a', 'g', '\x2', '\x2', 'u', 'v', '\a', 'u', '\x2', 
		'\x2', 'v', 'w', '\a', 'r', '\x2', '\x2', 'w', 'x', '\a', '\x63', '\x2', 
		'\x2', 'x', 'y', '\a', '\x65', '\x2', '\x2', 'y', 'z', '\a', 'g', '\x2', 
		'\x2', 'z', '\x1A', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', '\x46', 
		'\x2', '\x2', '|', '}', '\a', 'q', '\x2', '\x2', '}', '~', '\a', 'o', 
		'\x2', '\x2', '~', '\x7F', '\a', '\x63', '\x2', '\x2', '\x7F', '\x80', 
		'\a', 'k', '\x2', '\x2', '\x80', '\x81', '\a', 'p', '\x2', '\x2', '\x81', 
		'\x1C', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\a', '\x65', '\x2', 
		'\x2', '\x83', '\x84', '\a', 'n', '\x2', '\x2', '\x84', '\x85', '\a', 
		'\x63', '\x2', '\x2', '\x85', '\x86', '\a', 'u', '\x2', '\x2', '\x86', 
		'\x87', '\a', 'u', '\x2', '\x2', '\x87', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x89', '\a', '\x45', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'q', '\x2', '\x2', '\x8A', '\x8B', '\a', 'o', '\x2', '\x2', '\x8B', '\x8C', 
		'\a', 'o', '\x2', '\x2', '\x8C', '\x8D', '\a', '\x63', '\x2', '\x2', '\x8D', 
		'\x8E', '\a', 'p', '\x2', '\x2', '\x8E', '\x8F', '\a', '\x66', '\x2', 
		'\x2', '\x8F', '\x90', '\a', 'u', '\x2', '\x2', '\x90', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x92', '\a', '\x45', '\x2', '\x2', '\x92', '\x93', 
		'\a', 'q', '\x2', '\x2', '\x93', '\x94', '\a', 'o', '\x2', '\x2', '\x94', 
		'\x95', '\a', 'o', '\x2', '\x2', '\x95', '\x96', '\a', '\x63', '\x2', 
		'\x2', '\x96', '\x97', '\a', 'p', '\x2', '\x2', '\x97', '\x98', '\a', 
		'\x66', '\x2', '\x2', '\x98', '\"', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9A', '\a', 'O', '\x2', '\x2', '\x9A', '\x9B', '\a', 'q', '\x2', '\x2', 
		'\x9B', '\x9C', '\a', '\x66', '\x2', '\x2', '\x9C', '\x9D', '\a', 'g', 
		'\x2', '\x2', '\x9D', '\x9E', '\a', 'n', '\x2', '\x2', '\x9E', '$', '\x3', 
		'\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', 'T', '\x2', '\x2', '\xA0', 
		'\xA1', '\a', 'g', '\x2', '\x2', '\xA1', '\xA2', '\a', 'u', '\x2', '\x2', 
		'\xA2', '\xA3', '\a', 'w', '\x2', '\x2', '\xA3', '\xA4', '\a', 'n', '\x2', 
		'\x2', '\xA4', '\xA5', '\a', 'v', '\x2', '\x2', '\xA5', '&', '\x3', '\x2', 
		'\x2', '\x2', '\xA6', '\xA7', '\a', '/', '\x2', '\x2', '\xA7', '\xA8', 
		'\a', '/', '\x2', '\x2', '\xA8', '\xA9', '\a', '@', '\x2', '\x2', '\xA9', 
		'(', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\a', '\x45', '\x2', 
		'\x2', '\xAB', '\xAC', '\a', 'q', '\x2', '\x2', '\xAC', '\xAD', '\a', 
		'p', '\x2', '\x2', '\xAD', '\xAE', '\a', 'h', '\x2', '\x2', '\xAE', '\xAF', 
		'\a', 'k', '\x2', '\x2', '\xAF', '\xB0', '\a', 'i', '\x2', '\x2', '\xB0', 
		'*', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', '\a', 'S', '\x2', '\x2', 
		'\xB2', '\xB3', '\a', 'w', '\x2', '\x2', '\xB3', '\xB4', '\a', 'g', '\x2', 
		'\x2', '\xB4', '\xB5', '\a', 't', '\x2', '\x2', '\xB5', '\xB6', '\a', 
		'k', '\x2', '\x2', '\xB6', '\xB7', '\a', 'g', '\x2', '\x2', '\xB7', '\xB8', 
		'\a', 'u', '\x2', '\x2', '\xB8', ',', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBA', '\a', 'S', '\x2', '\x2', '\xBA', '\xBB', '\a', 'w', '\x2', '\x2', 
		'\xBB', '\xBC', '\a', 'g', '\x2', '\x2', '\xBC', '\xBD', '\a', 't', '\x2', 
		'\x2', '\xBD', '\xBE', '\a', '{', '\x2', '\x2', '\xBE', '.', '\x3', '\x2', 
		'\x2', '\x2', '\xBF', '\xC0', '\a', 'K', '\x2', '\x2', '\xC0', '\xC1', 
		'\a', 'p', '\x2', '\x2', '\xC1', '\xC2', '\a', 'v', '\x2', '\x2', '\xC2', 
		'\xC3', '\a', 'g', '\x2', '\x2', '\xC3', '\xC4', '\a', 't', '\x2', '\x2', 
		'\xC4', '\xC5', '\a', 'h', '\x2', '\x2', '\xC5', '\xC6', '\a', '\x63', 
		'\x2', '\x2', '\xC6', '\xC7', '\a', '\x65', '\x2', '\x2', '\xC7', '\xC8', 
		'\a', 'g', '\x2', '\x2', '\xC8', '\xC9', '\a', 'u', '\x2', '\x2', '\xC9', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\a', 'k', '\x2', 
		'\x2', '\xCB', '\xCC', '\a', 'p', '\x2', '\x2', '\xCC', '\xCD', '\a', 
		'v', '\x2', '\x2', '\xCD', '\xCE', '\a', 'g', '\x2', '\x2', '\xCE', '\xCF', 
		'\a', 't', '\x2', '\x2', '\xCF', '\xD0', '\a', 'h', '\x2', '\x2', '\xD0', 
		'\xD1', '\a', '\x63', '\x2', '\x2', '\xD1', '\xD2', '\a', '\x65', '\x2', 
		'\x2', '\xD2', '\xD3', '\a', 'g', '\x2', '\x2', '\xD3', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD5', '\a', 'x', '\x2', '\x2', '\xD5', 
		'\xD6', '\a', 'q', '\x2', '\x2', '\xD6', '\xD7', '\a', 'k', '\x2', '\x2', 
		'\xD7', '\xD8', '\a', '\x66', '\x2', '\x2', '\xD8', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\xD9', '\xDA', '\a', '\x64', '\x2', '\x2', '\xDA', '\xDB', 
		'\a', 'q', '\x2', '\x2', '\xDB', '\xDC', '\a', 'q', '\x2', '\x2', '\xDC', 
		'\xDD', '\a', 'n', '\x2', '\x2', '\xDD', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xDE', '\xDF', '\a', '\x66', '\x2', '\x2', '\xDF', '\xE0', '\a', 
		'\x63', '\x2', '\x2', '\xE0', '\xE1', '\a', 'v', '\x2', '\x2', '\xE1', 
		'\xE2', '\a', 'g', '\x2', '\x2', '\xE2', '\xE3', '\a', 'v', '\x2', '\x2', 
		'\xE3', '\xE4', '\a', 'k', '\x2', '\x2', '\xE4', '\xE5', '\a', 'o', '\x2', 
		'\x2', '\xE5', '\xE6', '\a', 'g', '\x2', '\x2', '\xE6', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xE7', '\xE8', '\a', 'k', '\x2', '\x2', '\xE8', 
		'\xE9', '\a', 'p', '\x2', '\x2', '\xE9', '\xEA', '\a', 'v', '\x2', '\x2', 
		'\xEA', ':', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xEC', '\a', 'u', '\x2', 
		'\x2', '\xEC', '\xED', '\a', 'v', '\x2', '\x2', '\xED', '\xEE', '\a', 
		't', '\x2', '\x2', '\xEE', '\xEF', '\a', 'k', '\x2', '\x2', '\xEF', '\xF0', 
		'\a', 'p', '\x2', '\x2', '\xF0', '\xF1', '\a', 'i', '\x2', '\x2', '\xF1', 
		'<', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF3', '\a', 'K', '\x2', '\x2', 
		'\xF3', '\xF4', '\a', 'G', '\x2', '\x2', '\xF4', '\xF5', '\a', 'p', '\x2', 
		'\x2', '\xF5', '\xF6', '\a', 'w', '\x2', '\x2', '\xF6', '\xF7', '\a', 
		'o', '\x2', '\x2', '\xF7', '\xF8', '\a', 'g', '\x2', '\x2', '\xF8', '\xF9', 
		'\a', 't', '\x2', '\x2', '\xF9', '\xFA', '\a', '\x63', '\x2', '\x2', '\xFA', 
		'\xFB', '\a', '\x64', '\x2', '\x2', '\xFB', '\xFC', '\a', 'n', '\x2', 
		'\x2', '\xFC', '\xFD', '\a', 'g', '\x2', '\x2', '\xFD', '>', '\x3', '\x2', 
		'\x2', '\x2', '\xFE', '\xFF', '\a', 'K', '\x2', '\x2', '\xFF', '\x100', 
		'\a', 'S', '\x2', '\x2', '\x100', '\x101', '\a', 'w', '\x2', '\x2', '\x101', 
		'\x102', '\a', 'g', '\x2', '\x2', '\x102', '\x103', '\a', 't', '\x2', 
		'\x2', '\x103', '\x104', '\a', '{', '\x2', '\x2', '\x104', '\x105', '\a', 
		'\x63', '\x2', '\x2', '\x105', '\x106', '\a', '\x64', '\x2', '\x2', '\x106', 
		'\x107', '\a', 'n', '\x2', '\x2', '\x107', '\x108', '\a', 'g', '\x2', 
		'\x2', '\x108', '@', '\x3', '\x2', '\x2', '\x2', '\x109', '\x10A', '\a', 
		'\x41', '\x2', '\x2', '\x10A', '\x42', '\x3', '\x2', '\x2', '\x2', '\x10B', 
		'\x10F', '\t', '\x2', '\x2', '\x2', '\x10C', '\x10E', '\t', '\x3', '\x2', 
		'\x2', '\x10D', '\x10C', '\x3', '\x2', '\x2', '\x2', '\x10E', '\x111', 
		'\x3', '\x2', '\x2', '\x2', '\x10F', '\x10D', '\x3', '\x2', '\x2', '\x2', 
		'\x10F', '\x110', '\x3', '\x2', '\x2', '\x2', '\x110', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\x111', '\x10F', '\x3', '\x2', '\x2', '\x2', '\x112', 
		'\x116', '\t', '\x4', '\x2', '\x2', '\x113', '\x115', '\t', '\x3', '\x2', 
		'\x2', '\x114', '\x113', '\x3', '\x2', '\x2', '\x2', '\x115', '\x118', 
		'\x3', '\x2', '\x2', '\x2', '\x116', '\x114', '\x3', '\x2', '\x2', '\x2', 
		'\x116', '\x117', '\x3', '\x2', '\x2', '\x2', '\x117', '\x46', '\x3', 
		'\x2', '\x2', '\x2', '\x118', '\x116', '\x3', '\x2', '\x2', '\x2', '\x119', 
		'\x11B', '\t', '\x5', '\x2', '\x2', '\x11A', '\x119', '\x3', '\x2', '\x2', 
		'\x2', '\x11B', '\x11C', '\x3', '\x2', '\x2', '\x2', '\x11C', '\x11A', 
		'\x3', '\x2', '\x2', '\x2', '\x11C', '\x11D', '\x3', '\x2', '\x2', '\x2', 
		'\x11D', '\x11E', '\x3', '\x2', '\x2', '\x2', '\x11E', '\x11F', '\b', 
		'$', '\x2', '\x2', '\x11F', 'H', '\x3', '\x2', '\x2', '\x2', '\x6', '\x2', 
		'\x10F', '\x116', '\x11C', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace OffSync.Apps.Codegen.Infra.PlantUml.Antlr
