//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Applications.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace OffSync.Apps.Codegen.Infra.PlantUml.Antlr {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IApplicationsListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class ApplicationsBaseListener : IApplicationsListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.application"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterApplication([NotNull] ApplicationsParser.ApplicationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.application"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitApplication([NotNull] ApplicationsParser.ApplicationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.title"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTitle([NotNull] ApplicationsParser.TitleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.title"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTitle([NotNull] ApplicationsParser.TitleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.aggregateRoots"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregateRoots([NotNull] ApplicationsParser.AggregateRootsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.aggregateRoots"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregateRoots([NotNull] ApplicationsParser.AggregateRootsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.aggregateRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAggregateRoot([NotNull] ApplicationsParser.AggregateRootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.aggregateRoot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAggregateRoot([NotNull] ApplicationsParser.AggregateRootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.domain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDomain([NotNull] ApplicationsParser.DomainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.domain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDomain([NotNull] ApplicationsParser.DomainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.classDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDefs([NotNull] ApplicationsParser.ClassDefsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.classDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDefs([NotNull] ApplicationsParser.ClassDefsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDef([NotNull] ApplicationsParser.ClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.classDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDef([NotNull] ApplicationsParser.ClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] ApplicationsParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] ApplicationsParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.properties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperties([NotNull] ApplicationsParser.PropertiesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.properties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperties([NotNull] ApplicationsParser.PropertiesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] ApplicationsParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] ApplicationsParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.commands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommands([NotNull] ApplicationsParser.CommandsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.commands"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommands([NotNull] ApplicationsParser.CommandsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] ApplicationsParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] ApplicationsParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.commandClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandClassDef([NotNull] ApplicationsParser.CommandClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.commandClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandClassDef([NotNull] ApplicationsParser.CommandClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.modelClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModelClassDef([NotNull] ApplicationsParser.ModelClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.modelClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModelClassDef([NotNull] ApplicationsParser.ModelClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.resultClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResultClassDef([NotNull] ApplicationsParser.ResultClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.resultClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResultClassDef([NotNull] ApplicationsParser.ResultClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.dependencies"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDependencies([NotNull] ApplicationsParser.DependenciesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.dependencies"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDependencies([NotNull] ApplicationsParser.DependenciesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.dependency"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDependency([NotNull] ApplicationsParser.DependencyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.dependency"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDependency([NotNull] ApplicationsParser.DependencyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.configClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfigClassDef([NotNull] ApplicationsParser.ConfigClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.configClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfigClassDef([NotNull] ApplicationsParser.ConfigClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.queries"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQueries([NotNull] ApplicationsParser.QueriesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.queries"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQueries([NotNull] ApplicationsParser.QueriesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuery([NotNull] ApplicationsParser.QueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuery([NotNull] ApplicationsParser.QueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.queryClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQueryClassDef([NotNull] ApplicationsParser.QueryClassDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.queryClassDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQueryClassDef([NotNull] ApplicationsParser.QueryClassDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.interfaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaces([NotNull] ApplicationsParser.InterfacesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.interfaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaces([NotNull] ApplicationsParser.InterfacesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.interfaceDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDefs([NotNull] ApplicationsParser.InterfaceDefsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.interfaceDefs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDefs([NotNull] ApplicationsParser.InterfaceDefsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.interfaceDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDef([NotNull] ApplicationsParser.InterfaceDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.interfaceDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDef([NotNull] ApplicationsParser.InterfaceDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.methods"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethods([NotNull] ApplicationsParser.MethodsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.methods"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethods([NotNull] ApplicationsParser.MethodsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod([NotNull] ApplicationsParser.MethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod([NotNull] ApplicationsParser.MethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.typeOrVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeOrVoid([NotNull] ApplicationsParser.TypeOrVoidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.typeOrVoid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeOrVoid([NotNull] ApplicationsParser.TypeOrVoidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] ApplicationsParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] ApplicationsParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] ApplicationsParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] ApplicationsParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SimpleType</c>
	/// labeled alternative in <see cref="ApplicationsParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleType([NotNull] ApplicationsParser.SimpleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SimpleType</c>
	/// labeled alternative in <see cref="ApplicationsParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleType([NotNull] ApplicationsParser.SimpleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>GenericType</c>
	/// labeled alternative in <see cref="ApplicationsParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericType([NotNull] ApplicationsParser.GenericTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GenericType</c>
	/// labeled alternative in <see cref="ApplicationsParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericType([NotNull] ApplicationsParser.GenericTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NullableSimpleType</c>
	/// labeled alternative in <see cref="ApplicationsParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullableSimpleType([NotNull] ApplicationsParser.NullableSimpleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NullableSimpleType</c>
	/// labeled alternative in <see cref="ApplicationsParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullableSimpleType([NotNull] ApplicationsParser.NullableSimpleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ReferenceType</c>
	/// labeled alternative in <see cref="ApplicationsParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReferenceType([NotNull] ApplicationsParser.ReferenceTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ReferenceType</c>
	/// labeled alternative in <see cref="ApplicationsParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReferenceType([NotNull] ApplicationsParser.ReferenceTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.dataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDataType([NotNull] ApplicationsParser.DataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.dataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDataType([NotNull] ApplicationsParser.DataTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.nullableDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullableDataType([NotNull] ApplicationsParser.NullableDataTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.nullableDataType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullableDataType([NotNull] ApplicationsParser.NullableDataTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArguments([NotNull] ApplicationsParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.typeArguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArguments([NotNull] ApplicationsParser.TypeArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.qualifiedId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedId([NotNull] ApplicationsParser.QualifiedIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.qualifiedId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedId([NotNull] ApplicationsParser.QualifiedIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId([NotNull] ApplicationsParser.IdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId([NotNull] ApplicationsParser.IdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ApplicationsParser.parameterName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterName([NotNull] ApplicationsParser.ParameterNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ApplicationsParser.parameterName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterName([NotNull] ApplicationsParser.ParameterNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace OffSync.Apps.Codegen.Infra.PlantUml.Antlr
